// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkK4lCb_NVTO5rdUbbskCHo5rQEKkaR8A',
    appId: '1:621062050446:web:64f0472fa2641fdbf62fdf',
    messagingSenderId: '621062050446',
    projectId: 'blood-camp-bano-qabil',
    authDomain: 'blood-camp-bano-qabil.firebaseapp.com',
    storageBucket: 'blood-camp-bano-qabil.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEEp_vhLM4x2xVZx1Zym1QtYxSB-TcKag',
    appId: '1:621062050446:android:4e57ae91a7794df4f62fdf',
    messagingSenderId: '621062050446',
    projectId: 'blood-camp-bano-qabil',
    storageBucket: 'blood-camp-bano-qabil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV_OJ9RuNhupIyY3MXthSx7Tx_-EF2Elw',
    appId: '1:621062050446:ios:35a61ecc62c55305f62fdf',
    messagingSenderId: '621062050446',
    projectId: 'blood-camp-bano-qabil',
    storageBucket: 'blood-camp-bano-qabil.firebasestorage.app',
    iosBundleId: 'com.example.bloodCampApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV_OJ9RuNhupIyY3MXthSx7Tx_-EF2Elw',
    appId: '1:621062050446:ios:35a61ecc62c55305f62fdf',
    messagingSenderId: '621062050446',
    projectId: 'blood-camp-bano-qabil',
    storageBucket: 'blood-camp-bano-qabil.firebasestorage.app',
    iosBundleId: 'com.example.bloodCampApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkK4lCb_NVTO5rdUbbskCHo5rQEKkaR8A',
    appId: '1:621062050446:web:42324e9cbd71d532f62fdf',
    messagingSenderId: '621062050446',
    projectId: 'blood-camp-bano-qabil',
    authDomain: 'blood-camp-bano-qabil.firebaseapp.com',
    storageBucket: 'blood-camp-bano-qabil.firebasestorage.app',
  );
}
